### PR TITLE
P4s ypp and add ja ko

### PR DESCRIPTION
**Pull request by kshman**
P4S: YPP strat (https://jp.finalfantasyxiv.com/lodestone/character/22408218/blog/4931930/) 
commonly uses in Japan DC.

Actually I don't know about cactbot coding rules. Would you please review and modify, if you like this PR.

Also I added Japanese and Korean output messages too.

### CODE REVIEW

**Comment by kshman** [comment]
Oh, sorry. I don't know why this Lint failed.
I recommend you can just copy some codes if it useful and discard this PR. :)

**Comment by Legends0** [comment]
Sorry I did not see this until now. There have been changes to resolve issues I had in the branch. I think I will be able to merge in at least the translations.

**Comment by Legends0** [comment]
I understand the strat. There is a general policy of cactbot to not force players into a certain strat, which is why I opted for generic calls rather than stating to stack for the people that do not need role call. I think most groups will be doing some variation of this strategy or less optimal such as stacking only south. Sometimes cactbot will opt to include the most common strategy if it makes the most sense to do so. They often will take requests to add options such as this if it is popular enough.

**Comment by Legends0** [comment]
I have copied the translations into the branch. For the strat change, I recommend putting that as a PR into the main cactbot once the branch here has been pushed to main.

**Pull request closed without merging**
