### PR TITLE
raidboss: simplify high concept towers logic

### PR DESCRIPTION
**Pull request by quisquous**

### CODE REVIEW

**Comment by quisquous** [comment]
Sorry to take such a heavy hand here, but I just had an idea that this could be simplified and got carried away.  <_<

This reduces the number of lines of code by half or so and (imo) makes it more generalized vs explicitly laying out every single case.  That makes it easier for me at least to read the logic and believe it's correct than to try to double check every single case, if that makes sense?

I think the other thought I had was that on the final HC2 towers, maybe we shouldn't prescribe which person to merge with? If you have green/purple towers (aka alpha/beta/beta/gamma required), then the beta people need to merge with either gamma or alpha (forming either tower).  I tested this with and without this PR, and this is (roughly) what the changes are logic-wise:

```diff
  Orange
  1 Long Alpha -> Avoid Purple -> Blue Tower (with Cherry or Grape)
- 2 Long Gamma -> Avoid Purple -> Blue Tower (with Mango)
+ 2 Long Gamma -> Avoid Purple -> Blue Tower (with Mango or Lime)

  Apple
  1 Long Beta -> Avoid Purple -> Avoid Blue
  2 No debuff -> Avoid Purple -> Get clone tether

  Cherry
  1 Long Gamma -> Avoid Purple -> Blue Tower (with Lime or Orange)
  2 Short Beta -> Purple Tower (with Pear) -> Get clone tether

  Lemon
  1 Short Gamma -> Purple Tower (with Mango) -> Avoid Blue Towers
  2 No debuff -> Avoid Purple -> Get clone tether

  Grape
  1 Three Stack -> Avoid Purple -> Blue Tower (with Lime or Orange)
- 2 Long Beta + Solo -> Avoid Purple -> Green Tower (with Lime)
+ 2 Long Beta + Solo -> Avoid Purple -> Green Tower (with Mango or Lime)

  Mango
  1 Short Beta -> Purple Tower (with Lemon) -> Avoid Blue Towers
- 2 Short Alpha -> Avoid Purple -> Blue Tower (with Orange)
+ 2 Short Alpha -> Avoid Purple -> Tower (with Grape or Orange)

  Pear
  1 Two Stack -> Avoid Purple -> Avoid Blue
  2 Short Gamma -> Purple Tower (with Cherry) -> Get clone tether

  Lime
  1 Short Alpha -> Avoid Purple -> Blue Tower (with Cherry or Grape)
- 2 Long Alpha + Two -> Avoid Purple -> Green Tower (with Grape)
+ 2 Long Alpha + Two -> Avoid Purple -> Tower (with Grape or Orange)
```

**Comment by quisquous** [comment]
cc https://github.com/quisquous/cactbot/pull/4919

**Comment by quisquous** [comment]
(I could also just put this up as its own PR too if that's easier, but I felt like I incrementally rewrote what you had, so it's not really its own thing either)

**Comment by Legends0** [comment]
Looks much better. Thanks for cleaning this up.

I think maybe a comment about the use of colorTowerAvoid twice could be helpful?

**Comment by quisquous** [comment]
> I think maybe a comment about the use of colorTowerAvoid twice could be helpful?

Sure, feel free to add one? I'm not quite sure what you want, so add what you think is missing, please!

**Pull request merged**
